function [fitresult, gof] = createFit(fst, fss)
%CREATEFIT(FST,FSS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fst
%      Y Output: fss
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Aug-2013 18:00:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fst, fss );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [588 -1.41439774753589 0.895749070995841 544.310933653579 0.912679152159066 0.557758767777108 475.596196012268 1.730521252753 0.647717780169855];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'fss vs. fst', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'fst' );
ylabel( 'fss' );
grid on


